# Generated by Django 4.0.5 on 2022-06-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariffID', models.IntegerField(default=714811)),
                ('money_day', models.IntegerField(default=1000)),
                ('money_h', models.IntegerField(default=150)),
                ('email', models.CharField(default='info@a1park.com', max_length=255)),
                ('phone', models.CharField(default='+7 495 646 87 02', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_barrier', models.FloatField(default=0.5)),
                ('pin_led_red', models.IntegerField(default=24)),
                ('pin_led_green', models.IntegerField(default=23)),
                ('pin_button', models.IntegerField(default=13)),
                ('pin_open', models.IntegerField(default=27)),
                ('pin_closed', models.IntegerField(default=22)),
                ('pin_loop1', models.IntegerField(default=5)),
                ('pin_loop2', models.IntegerField(default=6)),
                ('pin_infSensor', models.IntegerField(default=26)),
                ('loop1_type', models.BooleanField(default=True)),
                ('loop2_type', models.BooleanField(default=True)),
                ('infSensor_type', models.BooleanField(default=True)),
                ('buttonPrinter_type', models.BooleanField(default=True)),
                ('idVendor', models.IntegerField(default=3540)),
                ('idProduct', models.IntegerField(default=517)),
                ('in_ep', models.IntegerField(default=130)),
                ('out_ep', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_entry', models.BooleanField(choices=[(True, 'Въезд'), (False, 'Выезд')], default=True)),
                ('ip', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.standsettings')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parking', models.IntegerField()),
                ('secret_key', models.CharField(default='goe6t9sk41g09vm38v', max_length=255)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkingsettings')),
                ('stand_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_entry', to='api.stand')),
                ('stand_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_exit', to='api.stand')),
            ],
        ),
    ]
