# Generated by Django 4.0.5 on 2022-06-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standsettings',
            name='name_profile',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='standsettings',
            name='buttonPrinter_type',
            field=models.BooleanField(choices=[(True, 'Type NO'), (False, 'Type NC')], default=True),
        ),
        migrations.AlterField(
            model_name='standsettings',
            name='infSensor_type',
            field=models.BooleanField(choices=[(True, 'Type NO'), (False, 'Type NC')], default=True),
        ),
        migrations.AlterField(
            model_name='standsettings',
            name='loop1_type',
            field=models.BooleanField(choices=[(True, 'Type NO'), (False, 'Type NC')], default=True),
        ),
        migrations.AlterField(
            model_name='standsettings',
            name='loop2_type',
            field=models.BooleanField(choices=[(True, 'Type NO'), (False, 'Type NC')], default=True),
        ),
    ]
